### ISSUE TITLE
Define different levels for function progress

### ISSUE THREAD

**Issue by mattbruv** [bfbbdecomp/bfbb#183]
As discussed in the discord, I think we need to have different labels or `#define`'s for a function's progress. For example, a `#define` for functions which we can say without a doubt will match the original game's behavior but don't 100% match. This would allow us to build the game with our "almost perfect" code if we chose to, also it would allow us to track progress of functions that aren't perfect matches.

We need to come up with a labeling system or agree on ways to define a function's completeness.

**Comment by peb-adr** [comment]
my initial proposal:
`NOK_FUNCMATCH` - for functions you are 100% sure its functionally matching, probably because of minor scheduling issues. You should include at least one comment stating where the difference lies.
`NOK_NONMATCH` - for functions that are close but its not obvious they are functionally matching.
`NOK_WIP` - for functions you started working on but they no where near matching

maybe for a transition some kind of `NOK_UNCLEAR` might be useful. So we could change every #if 1, #ifndef NONMATCHING (or whatever other ways to exclude a function have been used so far) to this

**Comment by peb-adr** [comment]
maybe a way to define functional match would be:
If you can produce the original asm by merely reordering the lines of your assembly. Obviously it has to be clear that the behavior of the code doesnt change through this. But usually these issues happen within subsequent lines of variable assignments anyway right, so i think it should be clear for many cases
